/**
 * Created by EKO-LKB on 2017/6/12.
 */
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'
export const COM_LOADING = 'COM_LOADING'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const IS_SUBPAGE = 'IS_SUBPAGE'
export const GETLESSONTYPE = 'GETLESSONTYPELIST'
export const NEXT_PAGE = 'NEXT_PAGE'
export const SET_SEARCHTYPE = 'SET_SEARCHTYPE'
export const RESET_PAGE = 'RESET_PAGE'
export const GETVIDEOLIST = 'GETVIDEOLIST'
export const GETCOLLECTSTATUS = 'GETCOLLECTSTATUS'
export const GETVIDEOCONTENT = 'GETVIDEOCONTENT'
export const SETVIDEOPOPUP = 'SETVIDEOPOPUP'

/*article module*/
export const GETSWIPERLIST = 'GETSWIPERLIST'
export const GETARTICLETYPELIST = 'GETARTICLETYPELIST'
export const GETARTICLECONTENT = 'GETARTICLECONTENT'
export const NEXTCOMMENTSPAGE = 'NEXTCOMMENTSPAGE'
export const RESETCOMMENTSPAGE = 'RESETCOMMENTSPAGE'
export const GETTOTALCOMMENTS = 'GETTOTALCOMMENTS'
export const NEXTARTICLELISTPAGE = 'NEXTARTICLELISTPAGE'
export const RESETARTICLEPAGE = 'RESETARTICLEPAGE'
export const GETCOMMENT = 'GETCOMMENT'
export const ADDCOMMENT = 'ADDCOMMENT'
export const RESET_COMMENTS = 'RESET_COMMENTS'

/*mine module*/
export const GETCOLLECTIONLIST = 'GETCOLLECTIONLIST'
export const GETADMITSIGN = 'GETADMITSIGN'
export const GETSIGNNUM = 'GETSIGNNUM'
export const SIGNSUCCESS = 'SIGNSUCCESS'
